### PR TITLE
some problems which I experienced while using emencia

### PR DESCRIPTION
**Pull request by alesasnouski**
It was also a problem with email header on Russian when sending (python manage.py send_newsletter) (encoding problem) Don't know whether it's fixed or not :)

### CODE REVIEW

**Comment by Fantomas42** [comment]
Hi BlindHunter,

I will pull your commit asap, thank you for the contribution.

For the encoding problem, do you have non-ASCII character in the title of your newsletter ? If yes, use the "-v 0" option in your command. 

By downgrading the verbosity level, this error will not occurs anymore.

**Comment by alesasnouski** [comment]
I think it's also neccessary to write .sh script for cron : if 2 or more commands are started simultaneously a horrible things may occur :)

**Comment by alesasnouski** [comment]
Besides reconnecting solves issue partly : one letter (on which disconnect happened) is marked as ERROR ...
Though, it will be send later ...

**Comment by Fantomas42** [comment]
In your first commit,

you did not import SMTPServerDisconnected, so I don't think your patch work.

And reconnecting the smtp immediatly is not a really good solution.
So I will not apply it.

For the shell script, it's an idea but I don't know why you would launch the same command multiple time. :)

**Comment by alesasnouski** [comment]
Nevertheless, it's necessary to keep in mind gmail limitations, which can be also on other hosts : 
http://googlesystem.blogspot.com/2008/06/gmails-limitations-for-sending-messages.html

**Comment by Fantomas42** [comment]
Sending limitions are already handled in the SMTPServer model, with the **mails_hour** field and the **credits** method.

Configure it, your problem will disappear.

**Pull request closed without merging**
