### PR TITLE
fixed 999 sqlite3 variable limitation crashing the newsletter creation

### PR DESCRIPTION
**Pull request by danielsokolowski**
By default all available newsletter contacts are selected during mailing list creation which causes a  sqlite3 variable limitation crash, to avoid this the code has been modified so no contacts are automatically added and hence the sqlite3 limitation is only triggered when attempting to save.

### CODE REVIEW

**Comment by Fantomas42** [comment]
Hi danois,

thank you for your pull request, 
but if I understand well your patch, the mailing lists created will be empty of contacts ?

If so, I don't see the interest of creating a mailing list from the contact list admin view.

Does I miss something ?

Regards

**Comment by danielsokolowski** [comment]
Hi Fache,

No you are perfectly correct --- the mailing list starts empty --- 
however this allows to create mailing lists at least up to 999 whereas 
before an error would be thrown right away as the code greedtly tries to 
select all available contacts. This change allowed the client to split 
his contacts into A-H, H-Z etc.

So rather then critical failure, the limitation only creeps up if the 
limit is exceeded; in my mind an acceptable compromise to porting the 
site to  Portage SQL or MySQL

Thank you

**Comment by danielsokolowski** [comment]
Hi,

If I improved the patch to only perform the work around for sqlite database would you consider merging it then ?

**Comment by Fantomas42** [comment]
Hi,

yes it's may be a good idea. 
With a warning handle by the messages app, it can be a must.

Regards

**Comment by danielsokolowski** [comment]
Cherry pick this commit https://github.com/danols/emencia-django-newsletter/commit/af9d64a75e6c7aca9359b198b30793088d1623c3

Any further tweaks you require sir ? :)

**Comment by Fantomas42** [comment]
Hi danols,

thank you for your work and suggestion !

Fantomas42/emencia-django-newsletter@fb6fefb985888a9bc0294ad40a31cb68a5abdb1f should fix the issue.

As you can see I have a little bit adapted your code, but the essential is still present.

Regards.

**Comment by danielsokolowski** [comment]
Wonderful and thank you.

**Pull request closed without merging**
